#!/bin/bash

##############
# Detect modules needed
# By Bruno Goncalves < www.biglinux.com.br >
# 2022/03/01
# License GPL V2 or greater
###############

MODULE="$(./detectmodule.sh)"
FIRMWARE="$(pkexec env DISPLAY=$DISPLAY XAUTHORITY=$XAUTHORITY KDE_SESSION_VERSION=5 KDE_FULL_SESSION=true ${1+"$@"} ./detectfirmware.sh)"

if [ "$MODULE" = "" ]; then
    MODULE=$"MÓDULO: Nenhum módulo precisa ser instalado."
fi

if [ "$FIRMWARE" = "" ]; then
    FIRMWARE=$"FIRMWARE: Nenhum firmware precisa ser instalado."
fi

kdialog --msgbox "$MODULE
$FIRMWARE" --title $"Hardware"
